<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CityData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
          // Insert more City Master Seed Data
        DB::statement("INSERT IGNORE INTO `tbl_city` (state_id, city_name) VALUES
                ((select `id` from tbl_state where `short_name`='AP'),'Adilabad'),
                ((select `id` from tbl_state where `short_name`='AP'),'Anantapur'),
                ((select `id` from tbl_state where `short_name`='AP'),'Chittoor'),
                ((select `id` from tbl_state where `short_name`='AP'),'Kakinada'),
                ((select `id` from tbl_state where `short_name`='AP'),'Guntur'),
                ((select `id` from tbl_state where `short_name`='AP'),'Hyderabad'),
                ((select `id` from tbl_state where `short_name`='AP'),'Karimnagar'),
                ((select `id` from tbl_state where `short_name`='AP'),'Khammam'),
                ((select `id` from tbl_state where `short_name`='AP'),'Krishna'),
                ((select `id` from tbl_state where `short_name`='AP'),'Kurnool'),
                ((select `id` from tbl_state where `short_name`='AP'),'Mahbubnagar'),
                ((select `id` from tbl_state where `short_name`='AP'),'Medak'),
                ((select `id` from tbl_state where `short_name`='AP'),'Nalgonda'),
                ((select `id` from tbl_state where `short_name`='AP'),'Nizamabad'),
                ((select `id` from tbl_state where `short_name`='AP'),'Ongole'),
                ((select `id` from tbl_state where `short_name`='AP'),'Srikakulam'),
                ((select `id` from tbl_state where `short_name`='AP'),'Nellore'),
                ((select `id` from tbl_state where `short_name`='AP'),'Visakhapatnam'),
                ((select `id` from tbl_state where `short_name`='AP'),'Vizianagaram'),
                ((select `id` from tbl_state where `short_name`='AP'),'Warangal'),
                ((select `id` from tbl_state where `short_name`='AP'),'Eluru'),
                ((select `id` from tbl_state where `short_name`='AP'),'Kadapa'),

                ((select `id` from tbl_state where `short_name`='AS'),'Baksa'),
                ((select `id` from tbl_state where `short_name`='AS'),'Barpeta'),
                ((select `id` from tbl_state where `short_name`='AS'),'Bongaigaon'),
                ((select `id` from tbl_state where `short_name`='AS'),'Cachar'),
                ((select `id` from tbl_state where `short_name`='AS'),'Chirang'),
                ((select `id` from tbl_state where `short_name`='AS'),'Darrang'),
                ((select `id` from tbl_state where `short_name`='AS'),'Dima Hasao'),
                ((select `id` from tbl_state where `short_name`='AS'),'Dhubri'),
                ((select `id` from tbl_state where `short_name`='AS'),'Dibrugarh'),
                ((select `id` from tbl_state where `short_name`='AS'),'Goalpara'),
                ((select `id` from tbl_state where `short_name`='AS'),'Golaghat'),
                ((select `id` from tbl_state where `short_name`='AS'),'Hailakandi'),
                ((select `id` from tbl_state where `short_name`='AS'),'Jorhat'),
                ((select `id` from tbl_state where `short_name`='AS'),'Kamrup'),
                ((select `id` from tbl_state where `short_name`='AS'),'Kamrup Metropolitan'),
                ((select `id` from tbl_state where `short_name`='AS'),'Karbi Anglong'),
                ((select `id` from tbl_state where `short_name`='AS'),'Karimganj'),
                ((select `id` from tbl_state where `short_name`='AS'),'Kokrajhar'),
                ((select `id` from tbl_state where `short_name`='AS'),'Lakhimpur'),
                ((select `id` from tbl_state where `short_name`='AS'),'Marigaon'),
                ((select `id` from tbl_state where `short_name`='AS'),'Nagaon'),
                ((select `id` from tbl_state where `short_name`='AS'),'Nalbari'),
                ((select `id` from tbl_state where `short_name`='AS'),'Sibsagar'),
                ((select `id` from tbl_state where `short_name`='AS'),'Sonitpur'),
                ((select `id` from tbl_state where `short_name`='AS'),'Tinsukia'),
                ((select `id` from tbl_state where `short_name`='AS'),'Udalguri'),

                ((select `id` from tbl_state where `short_name`='BR'),'Araria'),
                ((select `id` from tbl_state where `short_name`='BR'),'Arwal'),
                ((select `id` from tbl_state where `short_name`='BR'),'Aurangabad'),
                ((select `id` from tbl_state where `short_name`='BR'),'Banka'),
                ((select `id` from tbl_state where `short_name`='BR'),'Begusarai'),
                ((select `id` from tbl_state where `short_name`='BR'),'Bhagalpur'),
                ((select `id` from tbl_state where `short_name`='BR'),'Bhojpur'),
                ((select `id` from tbl_state where `short_name`='BR'),'Buxar'),
                ((select `id` from tbl_state where `short_name`='BR'),'Darbhanga'),
                ((select `id` from tbl_state where `short_name`='BR'),'East Champaran'),
                ((select `id` from tbl_state where `short_name`='BR'),'Gaya'),
                ((select `id` from tbl_state where `short_name`='BR'),'Gopalganj'),
                ((select `id` from tbl_state where `short_name`='BR'),'Jamui'),
                ((select `id` from tbl_state where `short_name`='BR'),'Jehanabad'),
                ((select `id` from tbl_state where `short_name`='BR'),'Kaimur'),
                ((select `id` from tbl_state where `short_name`='BR'),'Katihar'),
                ((select `id` from tbl_state where `short_name`='BR'),'Khagaria'),
                ((select `id` from tbl_state where `short_name`='BR'),'Kishanganj'),
                ((select `id` from tbl_state where `short_name`='BR'),'Lakhisarai'),
                ((select `id` from tbl_state where `short_name`='BR'),'Madhepura'),
                ((select `id` from tbl_state where `short_name`='BR'),'Madhubani'),
                ((select `id` from tbl_state where `short_name`='BR'),'Munger'),
                ((select `id` from tbl_state where `short_name`='BR'),'Muzaffarpur'),
                ((select `id` from tbl_state where `short_name`='BR'),'Nalanda'),
                ((select `id` from tbl_state where `short_name`='BR'),'Nawada'),
                ((select `id` from tbl_state where `short_name`='BR'),'Patna'),
                ((select `id` from tbl_state where `short_name`='BR'),'Purnia'),
                ((select `id` from tbl_state where `short_name`='BR'),'Rohtas'),
                ((select `id` from tbl_state where `short_name`='BR'),'Saharsa'),
                ((select `id` from tbl_state where `short_name`='BR'),'Samastipur'),
                ((select `id` from tbl_state where `short_name`='BR'),'Saran'),
                ((select `id` from tbl_state where `short_name`='BR'),'Sheikhpura'),
                ((select `id` from tbl_state where `short_name`='BR'),'Sheohar'),
                ((select `id` from tbl_state where `short_name`='BR'),'Sitamarhi'),
                ((select `id` from tbl_state where `short_name`='BR'),'Siwan'),
                ((select `id` from tbl_state where `short_name`='BR'),'Supaul'),
                ((select `id` from tbl_state where `short_name`='BR'),'Vaishali'),
                ((select `id` from tbl_state where `short_name`='BR'),'West Champaran'),
                ((select `id` from tbl_state where `short_name`='BR'),'Chandigarh'),
                ((select `id` from tbl_state where `short_name`='CT'),'Bastar'),
                ((select `id` from tbl_state where `short_name`='CT'),'Bijapur'),
                ((select `id` from tbl_state where `short_name`='CT'),'Bilaspur'),
                ((select `id` from tbl_state where `short_name`='CT'),'Dantewada'),
                ((select `id` from tbl_state where `short_name`='CT'),'Dhamtari'),
                ((select `id` from tbl_state where `short_name`='CT'),'Durg'),
                ((select `id` from tbl_state where `short_name`='CT'),'Jashpur'),
                ((select `id` from tbl_state where `short_name`='CT'),'Janjgir-Champa'),
                ((select `id` from tbl_state where `short_name`='CT'),'Korba'),
                ((select `id` from tbl_state where `short_name`='CT'),'Koriya'),
                ((select `id` from tbl_state where `short_name`='CT'),'Kanker'),
                ((select `id` from tbl_state where `short_name`='CT'),'Kabirdham (Kawardha)'),
                ((select `id` from tbl_state where `short_name`='CT'),'Mahasamund'),
                ((select `id` from tbl_state where `short_name`='CT'),'Narayanpur'),
                ((select `id` from tbl_state where `short_name`='CT'),'Raigarh'),
                ((select `id` from tbl_state where `short_name`='CT'),'Rajnandgaon'),
                ((select `id` from tbl_state where `short_name`='CT'),'Raipur'),
                ((select `id` from tbl_state where `short_name`='CT'),'Surguja'),
                ((select `id` from tbl_state where `short_name`='DL'),'Central Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'East Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'New Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'North Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'North East Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'North West Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'South Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'South West Delhi'),
                ((select `id` from tbl_state where `short_name`='DL'),'West Delhi'),
                ((select `id` from tbl_state where `short_name`='GA'),'North Goa'),
                ((select `id` from tbl_state where `short_name`='GA'),'South Goa'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Ahmedabad'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Amreli district'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Anand'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Banaskantha'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Bharuch'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Bhavnagar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Dahod'),
                ((select `id` from tbl_state where `short_name`='GJ'),'The Dangs'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Gandhinagar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Jamnagar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Junagadh'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Kutch'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Kheda'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Mehsana'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Narmada'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Navsari'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Jamnagar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Junagadh'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Kutch'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Patan'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Panchmahal'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Porbandar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Rajkot'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Sabarkantha'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Surendranagar'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Surat'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Vyara'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Vadodara'),
                ((select `id` from tbl_state where `short_name`='GJ'),'Valsad'),

                ((select `id` from tbl_state where `short_name`='HR'),'Ambala'),
                ((select `id` from tbl_state where `short_name`='HR'),'Bhiwani'),
                ((select `id` from tbl_state where `short_name`='HR'),'Fatehabad'),
                ((select `id` from tbl_state where `short_name`='HR'),'Gurgaon'),
                ((select `id` from tbl_state where `short_name`='HR'),'Hissar'),
                ((select `id` from tbl_state where `short_name`='HR'),'Jhajjar'),

                ((select `id` from tbl_state where `short_name`='HR'),'Jind'),
                ((select `id` from tbl_state where `short_name`='HR'),'Karnal'),
                ((select `id` from tbl_state where `short_name`='HR'),'Kaithal'),
                ((select `id` from tbl_state where `short_name`='HR'),'Kurukshetra'),
                ((select `id` from tbl_state where `short_name`='HR'),'Mahendragarh'),
                ((select `id` from tbl_state where `short_name`='HR'),'Mewat'),

                ((select `id` from tbl_state where `short_name`='HR'),'Palwal'),
                ((select `id` from tbl_state where `short_name`='HR'),'Panchkula'),
                ((select `id` from tbl_state where `short_name`='HR'),'Panipat'),
                ((select `id` from tbl_state where `short_name`='HR'),'Rewari'),
                ((select `id` from tbl_state where `short_name`='HR'),'Rohtak'),
                ((select `id` from tbl_state where `short_name`='HR'),'Sirsa'),
                ((select `id` from tbl_state where `short_name`='HR'),'Sonipat'),
                ((select `id` from tbl_state where `short_name`='HR'),'Yamuna Nagar'),
                ((select `id` from tbl_state where `short_name`='HR'),'Faridabad'),

                ((select `id` from tbl_state where `short_name`='HP'),'Bilaspur'),
                ((select `id` from tbl_state where `short_name`='HP'),'Chamba'),
                ((select `id` from tbl_state where `short_name`='HP'),'Hamirpur'),
                ((select `id` from tbl_state where `short_name`='HP'),'Kangra'),
                ((select `id` from tbl_state where `short_name`='HP'),'Kinnaur'),
                ((select `id` from tbl_state where `short_name`='HP'),'Kullu'),

                ((select `id` from tbl_state where `short_name`='HP'),'Lahaul and Spiti'),
                ((select `id` from tbl_state where `short_name`='HP'),'Mandi'),
                ((select `id` from tbl_state where `short_name`='HP'),'Shimla'),
                ((select `id` from tbl_state where `short_name`='HP'),'Sirmaur'),
                ((select `id` from tbl_state where `short_name`='HP'),'Solan'),
                ((select `id` from tbl_state where `short_name`='HP'),'Una'),

                ((select `id` from tbl_state where `short_name`='JK'),'Anantnag'),
                ((select `id` from tbl_state where `short_name`='JK'),'Badgam'),
                ((select `id` from tbl_state where `short_name`='JK'),'Bandipora'),
                ((select `id` from tbl_state where `short_name`='JK'),'Baramulla'),
                ((select `id` from tbl_state where `short_name`='JK'),'Doda'),
                ((select `id` from tbl_state where `short_name`='JK'),'Ganderbal'),
                ((select `id` from tbl_state where `short_name`='JK'),'Jammu'),
                ((select `id` from tbl_state where `short_name`='JK'),'Kargil'),
                ((select `id` from tbl_state where `short_name`='JK'),'Kathua'),
                ((select `id` from tbl_state where `short_name`='JK'),'Kishtwar'),
                ((select `id` from tbl_state where `short_name`='JK'),'Kupwara'),
                ((select `id` from tbl_state where `short_name`='JK'),'Kulgam'),
                ((select `id` from tbl_state where `short_name`='JK'),'Leh'),
                ((select `id` from tbl_state where `short_name`='JK'),'Poonch'),
                ((select `id` from tbl_state where `short_name`='JK'),'Pulwama'),
                ((select `id` from tbl_state where `short_name`='JK'),'Rajauri'),
                ((select `id` from tbl_state where `short_name`='JK'),'Ramban'),
                ((select `id` from tbl_state where `short_name`='JK'),'Reasi'),
                ((select `id` from tbl_state where `short_name`='JK'),'Samba'),
                ((select `id` from tbl_state where `short_name`='JK'),'Shopian'),
                ((select `id` from tbl_state where `short_name`='JK'),'Srinagar'),
                ((select `id` from tbl_state where `short_name`='JK'),'Udhampur'),

                ((select `id` from tbl_state where `short_name`='JH'),'Bokaro'),
                ((select `id` from tbl_state where `short_name`='JH'),'Chatra'),
                ((select `id` from tbl_state where `short_name`='JH'),'Deoghar'),
                ((select `id` from tbl_state where `short_name`='JH'),'Dhanbad'),
                ((select `id` from tbl_state where `short_name`='JH'),'Dumka'),
                ((select `id` from tbl_state where `short_name`='JH'),'East Singhbhum'),
                ((select `id` from tbl_state where `short_name`='JH'),'Garhwa'),

                ((select `id` from tbl_state where `short_name`='JH'),'Giridih'),
                ((select `id` from tbl_state where `short_name`='JH'),'Godda'),
                ((select `id` from tbl_state where `short_name`='JH'),'Gumla'),
                ((select `id` from tbl_state where `short_name`='JH'),'Hazaribag'),
                ((select `id` from tbl_state where `short_name`='JH'),'Jamtara'),
                ((select `id` from tbl_state where `short_name`='JH'),'Khulti'),
                ((select `id` from tbl_state where `short_name`='JH'),'Koderma'),

                ((select `id` from tbl_state where `short_name`='JH'),'Latehar'),
                ((select `id` from tbl_state where `short_name`='JH'),'Lohardaga'),
                ((select `id` from tbl_state where `short_name`='JH'),'Pakur'),
                ((select `id` from tbl_state where `short_name`='JH'),'Palamu'),
                ((select `id` from tbl_state where `short_name`='JH'),'Ramgarh'),
                ((select `id` from tbl_state where `short_name`='JH'),'Ranchi'),
                ((select `id` from tbl_state where `short_name`='JH'),'Sahibganj'),
                ((select `id` from tbl_state where `short_name`='JH'),'Seraikela Kharsawan'),
                ((select `id` from tbl_state where `short_name`='JH'),'Simdega'),
                ((select `id` from tbl_state where `short_name`='JH'),'West Singhbhum'),

                ((select `id` from tbl_state where `short_name`='KA'),'Bagalkot'),
                ((select `id` from tbl_state where `short_name`='KA'),'Bangalore Rural'),
                ((select `id` from tbl_state where `short_name`='KA'),'Bangalore Urban'),
                ((select `id` from tbl_state where `short_name`='KA'),'Belgaum'),
                ((select `id` from tbl_state where `short_name`='KA'),'Bellary'),

                ((select `id` from tbl_state where `short_name`='KA'),'Bidar'),
                ((select `id` from tbl_state where `short_name`='KA'),'Bijapur'),
                ((select `id` from tbl_state where `short_name`='KA'),'Chamarajnagar'),
                ((select `id` from tbl_state where `short_name`='KA'),'Chikkamagaluru'),
                ((select `id` from tbl_state where `short_name`='KA'),'Chikkaballapur'),

                ((select `id` from tbl_state where `short_name`='KA'),'Chitradurga'),
                ((select `id` from tbl_state where `short_name`='KA'),'Davanagere'),
                ((select `id` from tbl_state where `short_name`='KA'),'Dharwad'),
                ((select `id` from tbl_state where `short_name`='KA'),'Dakshina Kannada'),
                ((select `id` from tbl_state where `short_name`='KA'),'Gadag'),
                ((select `id` from tbl_state where `short_name`='KA'),'Gulbarga'),
                ((select `id` from tbl_state where `short_name`='KA'),'Hassan'),
                ((select `id` from tbl_state where `short_name`='KA'),'Haveri district'),
                ((select `id` from tbl_state where `short_name`='KA'),'Kodagu'),
                ((select `id` from tbl_state where `short_name`='KA'),'Kolar'),

                ((select `id` from tbl_state where `short_name`='KA'),'Koppal'),
                ((select `id` from tbl_state where `short_name`='KA'),'Mandya'),
                ((select `id` from tbl_state where `short_name`='KA'),'Mysore'),
                ((select `id` from tbl_state where `short_name`='KA'),'Raichur'),
                ((select `id` from tbl_state where `short_name`='KA'),'Shimoga'),
                ((select `id` from tbl_state where `short_name`='KA'),'Tumkur'),
                ((select `id` from tbl_state where `short_name`='KA'),'Udupi'),
                ((select `id` from tbl_state where `short_name`='KA'),'Uttara Kannada'),
                ((select `id` from tbl_state where `short_name`='KA'),'Ramanagara'),
                ((select `id` from tbl_state where `short_name`='KA'),'Yadgir'),

                ((select `id` from tbl_state where `short_name`='KL'),'Alappuzha'),
                ((select `id` from tbl_state where `short_name`='KL'),'Ernakulam'),
                ((select `id` from tbl_state where `short_name`='KL'),'Idukki'),
                ((select `id` from tbl_state where `short_name`='KL'),'Kannur'),
                ((select `id` from tbl_state where `short_name`='KL'),'Kasaragod'),
                ((select `id` from tbl_state where `short_name`='KL'),'Kollam'),
                ((select `id` from tbl_state where `short_name`='KL'),'Kottayam'),
                ((select `id` from tbl_state where `short_name`='KL'),'Kozhikode'),
                ((select `id` from tbl_state where `short_name`='KL'),'Malappuram'),
                ((select `id` from tbl_state where `short_name`='KL'),'Palakkad'),
                ((select `id` from tbl_state where `short_name`='KL'),'Pathanamthitta'),
                ((select `id` from tbl_state where `short_name`='KL'),'Thrissur'),
                ((select `id` from tbl_state where `short_name`='KL'),'Thiruvananthapuram'),
                ((select `id` from tbl_state where `short_name`='KL'),'Wayanad'),

                ((select `id` from tbl_state where `short_name`='MP'),'Alirajpur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Anuppur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Ashok Nagar'),
                ((select `id` from tbl_state where `short_name`='MP'),'Balaghat'),
                ((select `id` from tbl_state where `short_name`='MP'),'Barwani'),
                ((select `id` from tbl_state where `short_name`='MP'),'Betul'),
                ((select `id` from tbl_state where `short_name`='MP'),'Bhind'),
                ((select `id` from tbl_state where `short_name`='MP'),'Bhopal'),
                ((select `id` from tbl_state where `short_name`='MP'),'Burhanpur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Chhatarpur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Chhindwara'),

                ((select `id` from tbl_state where `short_name`='MP'),'Damoh'),
                ((select `id` from tbl_state where `short_name`='MP'),'Datia'),
                ((select `id` from tbl_state where `short_name`='MP'),'Dewas'),
                ((select `id` from tbl_state where `short_name`='MP'),'Dhar'),
                ((select `id` from tbl_state where `short_name`='MP'),'Dindori'),
                ((select `id` from tbl_state where `short_name`='MP'),'Guna'),
                ((select `id` from tbl_state where `short_name`='MP'),'Gwalior'),
                ((select `id` from tbl_state where `short_name`='MP'),'Harda'),
                ((select `id` from tbl_state where `short_name`='MP'),'Hoshangabad'),
                ((select `id` from tbl_state where `short_name`='MP'),'Indore'),
                ((select `id` from tbl_state where `short_name`='MP'),'Jabalpur'),

                ((select `id` from tbl_state where `short_name`='MP'),'Jhabua'),
                ((select `id` from tbl_state where `short_name`='MP'),'Katni'),
                ((select `id` from tbl_state where `short_name`='MP'),'Khandwa (East Nimar)'),
                ((select `id` from tbl_state where `short_name`='MP'),'Khargone (West Nimar)'),
                ((select `id` from tbl_state where `short_name`='MP'),'Mandla'),
                ((select `id` from tbl_state where `short_name`='MP'),'Mandsaur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Morena'),
                ((select `id` from tbl_state where `short_name`='MP'),'Narsinghpur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Neemuch'),
                ((select `id` from tbl_state where `short_name`='MP'),'Panna'),
                ((select `id` from tbl_state where `short_name`='MP'),'Rewa'),

                ((select `id` from tbl_state where `short_name`='MP'),'Rajgarh'),
                ((select `id` from tbl_state where `short_name`='MP'),'Ratlam'),
                ((select `id` from tbl_state where `short_name`='MP'),'Raisen'),
                ((select `id` from tbl_state where `short_name`='MP'),'Sagar'),
                ((select `id` from tbl_state where `short_name`='MP'),'Satna'),
                ((select `id` from tbl_state where `short_name`='MP'),'Sehore'),
                ((select `id` from tbl_state where `short_name`='MP'),'Seoni'),
                ((select `id` from tbl_state where `short_name`='MP'),'Shahdol'),
                ((select `id` from tbl_state where `short_name`='MP'),'Shajapur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Sheopur'),
                ((select `id` from tbl_state where `short_name`='MP'),'Shivpuri'),

                ((select `id` from tbl_state where `short_name`='MP'),'Sidhi'),
                ((select `id` from tbl_state where `short_name`='MP'),'Singrauli'),
                ((select `id` from tbl_state where `short_name`='MP'),'Tikamgarh'),
                ((select `id` from tbl_state where `short_name`='MP'),'Ujjain'),
                ((select `id` from tbl_state where `short_name`='MP'),'Umaria'),
                ((select `id` from tbl_state where `short_name`='MP'),'Vidisha'),

                ((select `id` from tbl_state where `short_name`='MH'),'Ahmednagar'),
                ((select `id` from tbl_state where `short_name`='MH'),'Akola'),
                ((select `id` from tbl_state where `short_name`='MH'),'Amravati'),
                ((select `id` from tbl_state where `short_name`='MH'),'Aurangabad'),
                ((select `id` from tbl_state where `short_name`='MH'),'Bhandara'),
                ((select `id` from tbl_state where `short_name`='MH'),'Beed'),
                ((select `id` from tbl_state where `short_name`='MH'),'Buldhana'),

                ((select `id` from tbl_state where `short_name`='MH'),'Chandrapur'),
                ((select `id` from tbl_state where `short_name`='MH'),'Dhule'),
                ((select `id` from tbl_state where `short_name`='MH'),'Gadchiroli'),
                ((select `id` from tbl_state where `short_name`='MH'),'Gondia'),
                ((select `id` from tbl_state where `short_name`='MH'),'Hingoli'),
                ((select `id` from tbl_state where `short_name`='MH'),'Jalgaon'),
                ((select `id` from tbl_state where `short_name`='MH'),'Jalna'),
                ((select `id` from tbl_state where `short_name`='MH'),'Kolhapur'),

                ((select `id` from tbl_state where `short_name`='MH'),'Latur'),
                ((select `id` from tbl_state where `short_name`='MH'),'Mumbai City'),
                ((select `id` from tbl_state where `short_name`='MH'),'Mumbai suburban'),
                ((select `id` from tbl_state where `short_name`='MH'),'Nandurbar'),
                ((select `id` from tbl_state where `short_name`='MH'),'Nanded'),
                ((select `id` from tbl_state where `short_name`='MH'),'Nagpur'),
                ((select `id` from tbl_state where `short_name`='MH'),'Nashik'),

                ((select `id` from tbl_state where `short_name`='MH'),'Osmanabad'),
                ((select `id` from tbl_state where `short_name`='MH'),'Parbhani'),
                ((select `id` from tbl_state where `short_name`='MH'),'Pune'),
                ((select `id` from tbl_state where `short_name`='MH'),'Raigad'),
                ((select `id` from tbl_state where `short_name`='MH'),'Ratnagiri'),
                ((select `id` from tbl_state where `short_name`='MH'),'Sindhudurg'),
                ((select `id` from tbl_state where `short_name`='MH'),'Sangli'),
                ((select `id` from tbl_state where `short_name`='MH'),'Solapur'),
                ((select `id` from tbl_state where `short_name`='MH'),'Satara'),
                ((select `id` from tbl_state where `short_name`='MH'),'Thane'),
                ((select `id` from tbl_state where `short_name`='MH'),'Wardha'),
                ((select `id` from tbl_state where `short_name`='MH'),'Washim'),
                ((select `id` from tbl_state where `short_name`='MH'),'Yavatmal'),

                ((select `id` from tbl_state where `short_name`='MN'),'Bishnupur'),
                ((select `id` from tbl_state where `short_name`='MN'),'Churachandpur'),
                ((select `id` from tbl_state where `short_name`='MN'),'Chandel'),
                ((select `id` from tbl_state where `short_name`='MN'),'Imphal East'),
                ((select `id` from tbl_state where `short_name`='MN'),'Senapati'),
                ((select `id` from tbl_state where `short_name`='MN'),'Tamenglong'),
                ((select `id` from tbl_state where `short_name`='MN'),'Thoubal'),
                ((select `id` from tbl_state where `short_name`='MN'),'Ukhrul'),
                ((select `id` from tbl_state where `short_name`='MN'),'Imphal West'),

                ((select `id` from tbl_state where `short_name`='ML'),'East Garo Hills'),
                ((select `id` from tbl_state where `short_name`='ML'),'East Khasi Hills'),
                ((select `id` from tbl_state where `short_name`='ML'),'Jaintia Hills'),
                ((select `id` from tbl_state where `short_name`='ML'),'Ri Bhoi'),
                ((select `id` from tbl_state where `short_name`='ML'),'South Garo Hills'),
                ((select `id` from tbl_state where `short_name`='ML'),'West Garo Hills'),
                ((select `id` from tbl_state where `short_name`='ML'),'West Khasi Hills'),

                ((select `id` from tbl_state where `short_name`='MZ'),'Aizawl'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Champhai'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Kolasib'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Lawngtlai'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Lunglei'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Mamit'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Saiha'),
                ((select `id` from tbl_state where `short_name`='MZ'),'Serchhip'),

                ((select `id` from tbl_state where `short_name`='NL'),'Dimapur'),
                ((select `id` from tbl_state where `short_name`='NL'),'Kohima'),
                ((select `id` from tbl_state where `short_name`='NL'),'Mokokchung'),
                ((select `id` from tbl_state where `short_name`='NL'),'Mon'),
                ((select `id` from tbl_state where `short_name`='NL'),'Phek'),
                ((select `id` from tbl_state where `short_name`='NL'),'Tuensang'),
                ((select `id` from tbl_state where `short_name`='NL'),'Wokha'),
                ((select `id` from tbl_state where `short_name`='NL'),'Zunheboto'),

                ((select `id` from tbl_state where `short_name`='OR'),'Angul'),
                ((select `id` from tbl_state where `short_name`='OR'),'Boudh (Bauda)'),
                ((select `id` from tbl_state where `short_name`='OR'),'Bhadrak'),
                ((select `id` from tbl_state where `short_name`='OR'),'Balangir'),
                ((select `id` from tbl_state where `short_name`='OR'),'Bargarh (Baragarh)'),
                ((select `id` from tbl_state where `short_name`='OR'),'Balasore'),
                ((select `id` from tbl_state where `short_name`='OR'),'Cuttack'),
                ((select `id` from tbl_state where `short_name`='OR'),'Debagarh (Deogarh)'),

                ((select `id` from tbl_state where `short_name`='OR'),'Dhenkanal'),
                ((select `id` from tbl_state where `short_name`='OR'),'Ganjam'),
                ((select `id` from tbl_state where `short_name`='OR'),'Gajapati'),
                ((select `id` from tbl_state where `short_name`='OR'),'Jharsuguda'),
                ((select `id` from tbl_state where `short_name`='OR'),'Jajpur'),
                ((select `id` from tbl_state where `short_name`='OR'),'Jagatsinghpur'),
                ((select `id` from tbl_state where `short_name`='OR'),'Khordha'),

                ((select `id` from tbl_state where `short_name`='OR'),'Kendujhar (Keonjhar)'),
                ((select `id` from tbl_state where `short_name`='OR'),'Kalahandi'),
                ((select `id` from tbl_state where `short_name`='OR'),'Kandhamal'),
                ((select `id` from tbl_state where `short_name`='OR'),'Koraput'),
                ((select `id` from tbl_state where `short_name`='OR'),'Kendrapara'),
                ((select `id` from tbl_state where `short_name`='OR'),'Malkangiri'),
                ((select `id` from tbl_state where `short_name`='OR'),'Mayurbhanj'),
                ((select `id` from tbl_state where `short_name`='OR'),'Nabarangpur'),

                ((select `id` from tbl_state where `short_name`='OR'),'Nuapada'),
                ((select `id` from tbl_state where `short_name`='OR'),'Nayagarh'),
                ((select `id` from tbl_state where `short_name`='OR'),'Puri'),
                ((select `id` from tbl_state where `short_name`='OR'),'Rayagada'),
                ((select `id` from tbl_state where `short_name`='OR'),'Sambalpur'),
                ((select `id` from tbl_state where `short_name`='OR'),'Subarnapur (Sonepur)'),
                ((select `id` from tbl_state where `short_name`='OR'),'Sundergarh'),

                ((select `id` from tbl_state where `short_name`='PY'),'Karaikal'),
                ((select `id` from tbl_state where `short_name`='PY'),'Mahe'),
                ((select `id` from tbl_state where `short_name`='PY'),'Pondicherry'),
                ((select `id` from tbl_state where `short_name`='PY'),'Yanam'),

                ((select `id` from tbl_state where `short_name`='PB'),'Amritsar'),
                ((select `id` from tbl_state where `short_name`='PB'),'Barnala'),
                ((select `id` from tbl_state where `short_name`='PB'),'Bathinda'),
                ((select `id` from tbl_state where `short_name`='PB'),'Firozpur'),
                
                ((select `id` from tbl_state where `short_name`='PB'),'Faridkot'),
                ((select `id` from tbl_state where `short_name`='PB'),'Fatehgarh Sahib'),
                ((select `id` from tbl_state where `short_name`='PB'),'Fazilka'),
                ((select `id` from tbl_state where `short_name`='PB'),'Gurdaspur'),

                ((select `id` from tbl_state where `short_name`='PB'),'Hoshiarpur'),
                ((select `id` from tbl_state where `short_name`='PB'),'Jalandhar'),
                ((select `id` from tbl_state where `short_name`='PB'),'Kapurthala'),
                ((select `id` from tbl_state where `short_name`='PB'),'Ludhiana'),

                ((select `id` from tbl_state where `short_name`='PB'),'Mansa'),
                ((select `id` from tbl_state where `short_name`='PB'),'Moga'),
                ((select `id` from tbl_state where `short_name`='PB'),'Sri Muktsar Sahib'),
                ((select `id` from tbl_state where `short_name`='PB'),'Pathankot'),

                ((select `id` from tbl_state where `short_name`='PB'),'Patiala'),
                ((select `id` from tbl_state where `short_name`='PB'),'Rupnagar'),
                ((select `id` from tbl_state where `short_name`='PB'),'Ajitgarh (Mohali)'),
                ((select `id` from tbl_state where `short_name`='PB'),'Sangrur'),

                ((select `id` from tbl_state where `short_name`='PB'),'Nawanshahr'),
                ((select `id` from tbl_state where `short_name`='PB'),'Tarn Taran'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Ajmer'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Alwar'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Bikaner'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Barmer'),
                
                ((select `id` from tbl_state where `short_name`='RJ'),'Banswara'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Bharatpur'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Baran'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Bundi'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Bhilwara'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Churu'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Chittorgarh'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Dausa'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Dholpur'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Dungapur'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Ganganagar'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Hanumangarh'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Jhunjhunu'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Jalore'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Jodhpur'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Jaipur'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Jaisalmer'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Jhalawar'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Karauli'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Kota'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Nagaur'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Pali'),
                
                ((select `id` from tbl_state where `short_name`='RJ'),'Pratapgarh'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Rajsamand'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Sikar'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Sawai Madhopur'),

                ((select `id` from tbl_state where `short_name`='RJ'),'Sirohi'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Tonk'),
                ((select `id` from tbl_state where `short_name`='RJ'),'Udaipur'),

                ((select `id` from tbl_state where `short_name`='SK'),'East Sikkim'),
                ((select `id` from tbl_state where `short_name`='SK'),'North Sikkim'),
                ((select `id` from tbl_state where `short_name`='SK'),'South Sikkim'),
                ((select `id` from tbl_state where `short_name`='SK'),'West Sikkim'),
                
                ((select `id` from tbl_state where `short_name`='TN'),'Ariyalur'),
                ((select `id` from tbl_state where `short_name`='TN'),'Chennai'),
                ((select `id` from tbl_state where `short_name`='TN'),'Coimbatore'),
                ((select `id` from tbl_state where `short_name`='TN'),'Cuddalore'),
                
                ((select `id` from tbl_state where `short_name`='TN'),'Dharmapuri'),
                ((select `id` from tbl_state where `short_name`='TN'),'Dindigul'),
                ((select `id` from tbl_state where `short_name`='TN'),'Erode'),
                ((select `id` from tbl_state where `short_name`='TN'),'Kanchipuram'),

                ((select `id` from tbl_state where `short_name`='TN'),'Kanyakumari'),
                ((select `id` from tbl_state where `short_name`='TN'),'Karur'),
                ((select `id` from tbl_state where `short_name`='TN'),'Madurai'),

                ((select `id` from tbl_state where `short_name`='TN'),'Nagapattinam'),
                ((select `id` from tbl_state where `short_name`='TN'),'Nilgiris'),
                ((select `id` from tbl_state where `short_name`='TN'),'Namakkal'),
                ((select `id` from tbl_state where `short_name`='TN'),'Perambalur'),

                ((select `id` from tbl_state where `short_name`='TN'),'Pudukkottai'),
                ((select `id` from tbl_state where `short_name`='TN'),'Ramanathapuram'),
                ((select `id` from tbl_state where `short_name`='TN'),'Sivaganga'),
                ((select `id` from tbl_state where `short_name`='TN'),'Tirupur'),

                ((select `id` from tbl_state where `short_name`='TN'),'Tiruchirappalli'),
                ((select `id` from tbl_state where `short_name`='TN'),'Theni'),
                ((select `id` from tbl_state where `short_name`='TN'),'Tirunelveli'),

                ((select `id` from tbl_state where `short_name`='TN'),'Thanjavur'),
                ((select `id` from tbl_state where `short_name`='TN'),'Thoothukudi'),
                ((select `id` from tbl_state where `short_name`='TN'),'Tiruvallur'),
                ((select `id` from tbl_state where `short_name`='TN'),'Tiruvarur'),

                ((select `id` from tbl_state where `short_name`='TN'),'Tiruvannamalai'),
                ((select `id` from tbl_state where `short_name`='TN'),'Vellore'),
                ((select `id` from tbl_state where `short_name`='TN'),'Viluppuram'),
                ((select `id` from tbl_state where `short_name`='TN'),'Virudhunagar'),
                

                ((select `id` from tbl_state where `short_name`='TR'),'Dhalai'),
                ((select `id` from tbl_state where `short_name`='TR'),'North Tripura'),
                ((select `id` from tbl_state where `short_name`='TR'),'South Tripura'),
                ((select `id` from tbl_state where `short_name`='TR'),'Khowai'),
                ((select `id` from tbl_state where `short_name`='TR'),'West Tripura'),

                ((select `id` from tbl_state where `short_name`='UP'),'Agra'),
                ((select `id` from tbl_state where `short_name`='UP'),'Allahabad'),
                ((select `id` from tbl_state where `short_name`='UP'),'Aligarh'),
                ((select `id` from tbl_state where `short_name`='UP'),'Ambedkar Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Auraiya'),

                ((select `id` from tbl_state where `short_name`='UP'),'Azamgarh'),
                ((select `id` from tbl_state where `short_name`='UP'),'Barabanki'),
                ((select `id` from tbl_state where `short_name`='UP'),'Budaun'),
                ((select `id` from tbl_state where `short_name`='UP'),'Bagpat'),
                ((select `id` from tbl_state where `short_name`='UP'),'Bahraich'),
                ((select `id` from tbl_state where `short_name`='UP'),'Bijnor'),
                ((select `id` from tbl_state where `short_name`='UP'),'Ballia'),
                ((select `id` from tbl_state where `short_name`='UP'),'Banda'),
                ((select `id` from tbl_state where `short_name`='UP'),'Balrampur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Bareilly'),
                ((select `id` from tbl_state where `short_name`='UP'),'Basti'),
                ((select `id` from tbl_state where `short_name`='UP'),'Bulandshahr'),
                ((select `id` from tbl_state where `short_name`='UP'),'Chandauli'),
                ((select `id` from tbl_state where `short_name`='UP'),'Chhatrapati Shahuji Maharaj Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Chitrakoot'),
                
                
                ((select `id` from tbl_state where `short_name`='TR'),'Deoria'),
                ((select `id` from tbl_state where `short_name`='TR'),'Etah'),
                ((select `id` from tbl_state where `short_name`='TR'),'Kanshi Ram Nagar'),
                ((select `id` from tbl_state where `short_name`='TR'),'Etawah'),
                ((select `id` from tbl_state where `short_name`='TR'),'Firozabad'),

                ((select `id` from tbl_state where `short_name`='UP'),'Farrukhabad'),
                ((select `id` from tbl_state where `short_name`='UP'),'Fatehpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Faizabad'),
                ((select `id` from tbl_state where `short_name`='UP'),'Gautam Buddh Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Gonda'),

                ((select `id` from tbl_state where `short_name`='UP'),'Ghazipur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Gorakhpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Ghaziabad'),
                ((select `id` from tbl_state where `short_name`='UP'),'Hamirpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Hardoi'),
                ((select `id` from tbl_state where `short_name`='UP'),'Mahamaya Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Jhansi'),
                ((select `id` from tbl_state where `short_name`='UP'),'Jalaun'),
                ((select `id` from tbl_state where `short_name`='UP'),'Jyotiba Phule Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Jaunpur district'),
                ((select `id` from tbl_state where `short_name`='UP'),'Ramabai Nagar (Kanpur Dehat)'),
                ((select `id` from tbl_state where `short_name`='UP'),'Kannauj'),
                ((select `id` from tbl_state where `short_name`='UP'),'Kanpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Kaushambi'),
                ((select `id` from tbl_state where `short_name`='UP'),'Kushinagar'),

                ((select `id` from tbl_state where `short_name`='UP'),'Lalitpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Lucknow'),
                ((select `id` from tbl_state where `short_name`='UP'),'Mau'),
                ((select `id` from tbl_state where `short_name`='UP'),'Meerut'),
                ((select `id` from tbl_state where `short_name`='UP'),'Maharajganj'),

                ((select `id` from tbl_state where `short_name`='UP'),'Mahoba'),
                ((select `id` from tbl_state where `short_name`='UP'),'Mirzapur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Moradabad'),
                ((select `id` from tbl_state where `short_name`='UP'),'Mainpuri'),
                ((select `id` from tbl_state where `short_name`='UP'),'Mathura'),
                ((select `id` from tbl_state where `short_name`='UP'),'Muzaffarnagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Panchsheel Nagar district (Hapur)'),
                ((select `id` from tbl_state where `short_name`='UP'),'Pilibhit'),
                ((select `id` from tbl_state where `short_name`='UP'),'Shamli'),
                ((select `id` from tbl_state where `short_name`='UP'),'Pratapgarh'),
                ((select `id` from tbl_state where `short_name`='UP'),'Rampur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Raebareli'),
                ((select `id` from tbl_state where `short_name`='UP'),'Saharanpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Sitapur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Shahjahanpur'),

                ((select `id` from tbl_state where `short_name`='UP'),'Sant Kabir Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Siddharthnagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Sonbhadra'),
                ((select `id` from tbl_state where `short_name`='UP'),'Sant Ravidas Nagar'),
                ((select `id` from tbl_state where `short_name`='UP'),'Sultanpur'),
                ((select `id` from tbl_state where `short_name`='UP'),'Shravasti'),
                ((select `id` from tbl_state where `short_name`='UP'),'Unnao'),
                ((select `id` from tbl_state where `short_name`='UP'),'Varanasi'),

                ((select `id` from tbl_state where `short_name`='WB'),'Kolkata'),
                ((select `id` from tbl_state where `short_name`='WB'),'Asansol'),
                ((select `id` from tbl_state where `short_name`='WB'),'Siliguri'),
                ((select `id` from tbl_state where `short_name`='WB'),'Durgapur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Burdwan'),
                ((select `id` from tbl_state where `short_name`='WB'),'English Bazar'),
                ((select `id` from tbl_state where `short_name`='WB'),'Baharampur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Habra'),

                ((select `id` from tbl_state where `short_name`='WB'),'Kharagpur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Shantipur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Dankuni'),
                ((select `id` from tbl_state where `short_name`='WB'),'Dhulian'),
                ((select `id` from tbl_state where `short_name`='WB'),'Ranaghat'),
                ((select `id` from tbl_state where `short_name`='WB'),'Haldia'),
                ((select `id` from tbl_state where `short_name`='WB'),'Raiganj'),
                ((select `id` from tbl_state where `short_name`='WB'),'Krishnanagar'),

                
                ((select `id` from tbl_state where `short_name`='WB'),'Nabadwip'),
                ((select `id` from tbl_state where `short_name`='WB'),'Medinipur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Jalpaiguri'),
                ((select `id` from tbl_state where `short_name`='WB'),'Balurghat'),
                ((select `id` from tbl_state where `short_name`='WB'),'Basirhat'),
                ((select `id` from tbl_state where `short_name`='WB'),'Bankura'),
                ((select `id` from tbl_state where `short_name`='WB'),'Chakdaha'),
                ((select `id` from tbl_state where `short_name`='WB'),'Darjeeling'),

                ((select `id` from tbl_state where `short_name`='WB'),'Alipurduar'),
                ((select `id` from tbl_state where `short_name`='WB'),'Purulia'),
                ((select `id` from tbl_state where `short_name`='WB'),'Jangipur'),
                ((select `id` from tbl_state where `short_name`='WB'),'Bangaon'),
                ((select `id` from tbl_state where `short_name`='WB'),'Cooch Behar')


                ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
